"""Plugging into the project

Revision ID: c0fa1cc0e7a8
Revises: 5afed8083bd4
Create Date: 2021-12-16 08:50:06.453140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0fa1cc0e7a8'
down_revision = '5afed8083bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_no', sa.String(length=12), nullable=False),
    sa.Column('unit_amount', sa.String(length=10), nullable=False),
    sa.Column('ref1', sa.String(length=25), nullable=False),
    sa.Column('ref2', sa.String(length=255), nullable=True),
    sa.Column('delivery_remark', sa.String(length=255), nullable=True),
    sa.Column('cod_value', sa.String(length=255), nullable=True),
    sa.Column('commission_type', sa.Integer(), nullable=False),
    sa.Column('cod_currency', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref1')
    )
    op.create_index(op.f('ix_shipment_id'), 'shipment', ['id'], unique=False)
    op.create_table('shipment_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=255), nullable=False),
    sa.Column('zipcode', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('street_and_number', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.Column('fax', sa.String(length=255), nullable=True),
    sa.Column('notify_gsm', sa.String(length=255), nullable=False),
    sa.Column('notify_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_address_id'), 'shipment_address', ['id'], unique=False)
    op.create_table('shipment_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_product_id'), 'shipment_product', ['id'], unique=False)
    op.create_table('shipment_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_status_id'), 'shipment_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_status_id'), table_name='shipment_status')
    op.drop_table('shipment_status')
    op.drop_index(op.f('ix_shipment_product_id'), table_name='shipment_product')
    op.drop_table('shipment_product')
    op.drop_index(op.f('ix_shipment_address_id'), table_name='shipment_address')
    op.drop_table('shipment_address')
    op.drop_index(op.f('ix_shipment_id'), table_name='shipment')
    op.drop_table('shipment')
    # ### end Alembic commands ###
